version: '3'
services:
  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
#      - "/Users/touch/prometheus/prometheus:/data/lib/prometheus"
#      - "/Users/touch/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/home/admin/data/prometheus/prometheus:/data/lib/prometheus"
      - "/home/admin/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  node-exporter:
    image: prom/node-exporter
    restart: always
    container_name: node-exporters
    ports:
      - "9100:9100"
  grafana:
    image: grafana/grafana:5.0.0
    restart: always
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
 #     - "/Users/touch/grafana:/var/lib/grafana"
      - "/home/admin/data/grafana:/var/lib/grafana"
      - "/home/admin/logs/grafana:/var/log/grafana"
